"""removed body and post from title

Revision ID: 212457fa6819
Revises: c37ac8e13eb2
Create Date: 2019-04-10 13:24:00.321478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '212457fa6819'
down_revision = 'c37ac8e13eb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post') as batch_op:
        batch_op.drop_index('ix_post_title')
        batch_op.drop_column('body')
        batch_op.drop_column('title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=200), nullable=True))
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.create_index('ix_post_title', 'post', ['title'], unique=False)
    # ### end Alembic commands ###
