"""add title and body to post table

Revision ID: 56f5accb2bbe
Revises: 212457fa6819
Create Date: 2019-04-10 13:30:46.455129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56f5accb2bbe'
down_revision = '212457fa6819'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('body', sa.Text(), nullable=True))
    op.add_column('post', sa.Column('title', sa.Text(), nullable=True))
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_title'), table_name='post')
    op.drop_column('post', 'title')
    op.drop_column('post', 'body')
    # ### end Alembic commands ###
