"""create Ticker Table

Revision ID: be48e2ebd998
Revises: b781718ebc77
Create Date: 2019-03-29 18:21:29.592078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be48e2ebd998'
down_revision = 'b781718ebc77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=5), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ticker_name'), 'ticker', ['name'], unique=False)
    op.create_index(op.f('ix_ticker_sector'), 'ticker', ['sector'], unique=False)
    op.create_index(op.f('ix_ticker_symbol'), 'ticker', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_symbol'), table_name='ticker')
    op.drop_index(op.f('ix_ticker_sector'), table_name='ticker')
    op.drop_index(op.f('ix_ticker_name'), table_name='ticker')
    op.drop_table('ticker')
    # ### end Alembic commands ###
