"""removed body and title under post

Revision ID: c37ac8e13eb2
Revises: 02300d49db40
Create Date: 2019-04-09 19:23:16.230414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37ac8e13eb2'
down_revision = '02300d49db40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_title', table_name='post')
    op.drop_column('post', 'body')
    op.drop_column('post', 'title')
    op.create_index(op.f('ix_ticker_exchange'), 'ticker', ['exchange'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ticker_exchange'), table_name='ticker')
    op.add_column('post', sa.Column('title', sa.VARCHAR(length=200), nullable=True))
    op.add_column('post', sa.Column('body', sa.VARCHAR(length=140), nullable=True))
    op.create_index('ix_post_title', 'post', ['title'], unique=False)
    # ### end Alembic commands ###
