"""create posts_tickers relationship and table

Revision ID: fa71bf3a8fc7
Revises: cf2b45a6e851
Create Date: 2019-04-01 18:02:57.211667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa71bf3a8fc7'
down_revision = 'cf2b45a6e851'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts_tickers',
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.Column('ticker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.ForeignKeyConstraint(['ticker_id'], ['ticker.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts_tickers')
    # ### end Alembic commands ###
